name: CI
on:
  push:
    # Comment out in project
    #branches-ignore:
    #  - master
jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest] # windows-latest fails for some reason
        php-versions: ['7.2', '7.3', '7.4']
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, curl, zip
          coverage: xdebug
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer
          restore-keys: ${{ runner.os }}-composer
      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
      - name: Check Code Style with PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run -vvv
      - name: Unit Test with PHPUnit
        run: vendor/bin/phpunit --testdox --coverage-text
      - name: Test Type Correctness with Psalm
        run: vendor/bin/psalm
